version: 2

before:
  hooks:
    - go mod tidy

builds:
  # Linux 构建
  - id: "linux"
    binary: dnsflux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      # - arm64
    hooks:
      pre: |
        go generate ./...

  # Windows 和 Darwin 构建
  - id: "others"
    binary: dnsflux
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      # - darwin
    goarch:
      - amd64
      - arm64
    # ignore:
    #   - goos: darwin
    #     goarch: arm64
    # hooks:
    #   pre: go generate ./...

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:' 